services:
  postgres:
    image: postgres:16
    container_name: nexus_postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: nexus
      POSTGRES_PASSWORD: nexus_password
      POSTGRES_DB: nexus
    volumes:
      - nexus_pg_data:/var/lib/postgresql/data

volumes:
  nexus_pg_data:

